# Top Navigation Bar
title: Mission Sites
subtitle: "Website solutions for churches and small businesses."
logo: "/assets/images/88x88.png"

# Google Description
description: Website solutions for churches and small businesses.

# Build settings
title_separator: "|"
repository: mission-sites/mission-sites.com
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin:
search: false
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
permalink: /
include:
  - _pages
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
